# Balanceamento de Jogo

# Combate
COMBAT_DAMAGE_MULTIPLIER = 1.2
CRITICAL_CHANCE = 0.15  # 15%
CRITICAL_MULTIPLIER = 2.0

# Defesa
ARMOR_REDUCTION_FACTOR = 0.2
DODGE_CHANCE_MULTIPLIER = 0.1

# Magia
SPELL_DAMAGE_MULTIPLIER = 1.0
MANA_COST_MULTIPLIER = 1.0
SPELL_COOLDOWN_BASE = 1.0

# Crafting
CRAFTING_TIME_MULTIPLIER = 1.0
CRAFTING_XP_MULTIPLIER = 1.5
QUALITY_SUCCESS_THRESHOLD = 0.7

# Economia
BASE_NPC_SELL_PRICE = 100
NPC_BUY_PERCENTAGE = 0.5  # NPCs compram por 50% do valor
INFLATION_RATE = 0.01  # 1% por semana

# IA
OLLAMA_TIMEOUT_SECONDS = 5
OLLAMA_CONTEXT_LENGTH = 500
DIALOGUE_CACHE_TTL = 3600  # 1 hora

# Rewards
MOB_KILL_XP_BASE = 100
QUEST_XP_MULTIPLIER = 2.0
CRAFTING_XP_BASE = 50
